name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [dev]
    environment: ${{ matrix.environment }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Update function name
      run: |
        $env = "${{ matrix.environment }}".ToLower().substring(0, 1)
        $func_app_name = "corp-{0}-01-creditcheck-func" -f $env
        Write-Output "::set-output name=FUNCAPP_NAME::$func_app_name"
        Write-Output {{ env.FUNC_APP_NAME }}
        
    - name: echo function name
      run: |
        Write-Output ${{ steps.environment.outputs.FUNCAPP_NAME }}
