name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [dev]
    environment: ${{ matrix.environment }}
    env:
      FUNC_APP_NAME: ""
      
    steps:
    - name: Update function name
      run: |
        $env = "${{ matrix.environment }}".ToLower().substring(0, 1)
        $func_app_name = "corp-{0}-01-creditcheck-func" -f $env
        echo "$FUNCAPP_NAME=$func_app_name" >> $GITHUB_ENV
        Write-Output "env.$FUNCAPP_NAME"
        echo "$FUNCAPP_NAME"
        
    - name: echo function name
      run: |
        Write-Output "$FUNCAPP_NAME"
        echo echo ${{ env.FUNCAPP_NAME }}
