name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [dev]
    environment: ${{ matrix.environment }}
    
    env:
      SOURCE_LOCATION: ${{ github.workspace }}
      
    steps:
        
    - name: Copy Eviny Developer portal
      run: |
        ls ${{ env.SOURCE_LOCATION }}
      
    - name: Run bat script on PowerShell
      shell: pwsh
      working-directory: ${{ env.SOURCE_LOCATION }}
      run: '${{ github.workspace }}\Tools\ConfigureJIT.ps1'
  
    - name: Power shell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ${{ github.workspace }}\Tools\ConfigureJIT.ps1
        azPSVersion: "latest"
