name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [dev]
    environment: ${{ matrix.environment }}
      
    steps:
    - name: Update function name
      id: environment
      run: |
        $env = "${{ matrix.environment }}".ToLower().substring(0, 1)
        $az_function_name = "corp-{0}-01-creditcheck-func" -f $env
        echo "::set-output name=AZ_FUNCIOTN_NAME::$az_function_name -f $env"
       
    - name: echo function name
      run: |
        echo ${{steps.environment.outputs.AZ_FUNCIOTN_NAME}}
